package com.elite.cirworld.persist.mapper;

import com.elite.cirworld.persist.model.CyclingPlan;
import com.elite.cirworld.persist.model.CyclingPlanExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CyclingPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    int countByExample(CyclingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    int deleteByExample(CyclingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    int insert(CyclingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    int insertSelective(CyclingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    List<CyclingPlan> selectByExample(CyclingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CyclingPlan record, @Param("example") CyclingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CyclingPlan record, @Param("example") CyclingPlanExample example);
}