package com.elite.cirworld.persist.mapper;

import com.elite.cirworld.persist.model.CyclingMonth;
import com.elite.cirworld.persist.model.CyclingMonthExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CyclingMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int countByExample(CyclingMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int deleteByExample(CyclingMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int insert(CyclingMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int insertSelective(CyclingMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    List<CyclingMonth> selectByExample(CyclingMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    CyclingMonth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CyclingMonth record, @Param("example") CyclingMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CyclingMonth record, @Param("example") CyclingMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CyclingMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CyclingMonth record);
}