package com.elite.cirworld.persist.mapper;

import com.elite.cirworld.persist.model.CyclingPart;
import com.elite.cirworld.persist.model.CyclingPartExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CyclingPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int countByExample(CyclingPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int deleteByExample(CyclingPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int insert(CyclingPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int insertSelective(CyclingPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    List<CyclingPart> selectByExample(CyclingPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    CyclingPart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CyclingPart record, @Param("example") CyclingPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CyclingPart record, @Param("example") CyclingPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CyclingPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_part
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CyclingPart record);
}