package com.elite.cirworld.persist.model;

public class CyclingTotal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.distance
     *
     * @mbggenerated
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.max_speed
     *
     * @mbggenerated
     */
    private Float maxSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.average_speed
     *
     * @mbggenerated
     */
    private Float averageSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.max_altitude
     *
     * @mbggenerated
     */
    private Float maxAltitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.min_altitude
     *
     * @mbggenerated
     */
    private Float minAltitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.max_longitude
     *
     * @mbggenerated
     */
    private Float maxLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.min_longitude
     *
     * @mbggenerated
     */
    private Float minLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.max_latitude
     *
     * @mbggenerated
     */
    private Float maxLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_total.min_latitude
     *
     * @mbggenerated
     */
    private Float minLatitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.uid
     *
     * @return the value of cycling_total.uid
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.uid
     *
     * @param uid the value for cycling_total.uid
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.distance
     *
     * @return the value of cycling_total.distance
     * @mbggenerated
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.distance
     *
     * @param distance the value for cycling_total.distance
     * @mbggenerated
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.max_speed
     *
     * @return the value of cycling_total.max_speed
     * @mbggenerated
     */
    public Float getMaxSpeed() {
        return maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.max_speed
     *
     * @param maxSpeed the value for cycling_total.max_speed
     * @mbggenerated
     */
    public void setMaxSpeed(Float maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.average_speed
     *
     * @return the value of cycling_total.average_speed
     * @mbggenerated
     */
    public Float getAverageSpeed() {
        return averageSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.average_speed
     *
     * @param averageSpeed the value for cycling_total.average_speed
     * @mbggenerated
     */
    public void setAverageSpeed(Float averageSpeed) {
        this.averageSpeed = averageSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.max_altitude
     *
     * @return the value of cycling_total.max_altitude
     * @mbggenerated
     */
    public Float getMaxAltitude() {
        return maxAltitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.max_altitude
     *
     * @param maxAltitude the value for cycling_total.max_altitude
     * @mbggenerated
     */
    public void setMaxAltitude(Float maxAltitude) {
        this.maxAltitude = maxAltitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.min_altitude
     *
     * @return the value of cycling_total.min_altitude
     * @mbggenerated
     */
    public Float getMinAltitude() {
        return minAltitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.min_altitude
     *
     * @param minAltitude the value for cycling_total.min_altitude
     * @mbggenerated
     */
    public void setMinAltitude(Float minAltitude) {
        this.minAltitude = minAltitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.max_longitude
     *
     * @return the value of cycling_total.max_longitude
     * @mbggenerated
     */
    public Float getMaxLongitude() {
        return maxLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.max_longitude
     *
     * @param maxLongitude the value for cycling_total.max_longitude
     * @mbggenerated
     */
    public void setMaxLongitude(Float maxLongitude) {
        this.maxLongitude = maxLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.min_longitude
     *
     * @return the value of cycling_total.min_longitude
     * @mbggenerated
     */
    public Float getMinLongitude() {
        return minLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.min_longitude
     *
     * @param minLongitude the value for cycling_total.min_longitude
     * @mbggenerated
     */
    public void setMinLongitude(Float minLongitude) {
        this.minLongitude = minLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.max_latitude
     *
     * @return the value of cycling_total.max_latitude
     * @mbggenerated
     */
    public Float getMaxLatitude() {
        return maxLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.max_latitude
     *
     * @param maxLatitude the value for cycling_total.max_latitude
     * @mbggenerated
     */
    public void setMaxLatitude(Float maxLatitude) {
        this.maxLatitude = maxLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_total.min_latitude
     *
     * @return the value of cycling_total.min_latitude
     * @mbggenerated
     */
    public Float getMinLatitude() {
        return minLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_total.min_latitude
     *
     * @param minLatitude the value for cycling_total.min_latitude
     * @mbggenerated
     */
    public void setMinLatitude(Float minLatitude) {
        this.minLatitude = minLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_total
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CyclingTotal other = (CyclingTotal) that;
        return (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
                && (this.getDistance() == null ? other.getDistance() == null : this.getDistance().equals(other.getDistance()))
                && (this.getMaxSpeed() == null ? other.getMaxSpeed() == null : this.getMaxSpeed().equals(other.getMaxSpeed()))
                && (this.getAverageSpeed() == null ? other.getAverageSpeed() == null : this.getAverageSpeed().equals(other.getAverageSpeed()))
                && (this.getMaxAltitude() == null ? other.getMaxAltitude() == null : this.getMaxAltitude().equals(other.getMaxAltitude()))
                && (this.getMinAltitude() == null ? other.getMinAltitude() == null : this.getMinAltitude().equals(other.getMinAltitude()))
                && (this.getMaxLongitude() == null ? other.getMaxLongitude() == null : this.getMaxLongitude().equals(other.getMaxLongitude()))
                && (this.getMinLongitude() == null ? other.getMinLongitude() == null : this.getMinLongitude().equals(other.getMinLongitude()))
                && (this.getMaxLatitude() == null ? other.getMaxLatitude() == null : this.getMaxLatitude().equals(other.getMaxLatitude()))
                && (this.getMinLatitude() == null ? other.getMinLatitude() == null : this.getMinLatitude().equals(other.getMinLatitude()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_total
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getDistance() == null) ? 0 : getDistance().hashCode());
        result = prime * result + ((getMaxSpeed() == null) ? 0 : getMaxSpeed().hashCode());
        result = prime * result + ((getAverageSpeed() == null) ? 0 : getAverageSpeed().hashCode());
        result = prime * result + ((getMaxAltitude() == null) ? 0 : getMaxAltitude().hashCode());
        result = prime * result + ((getMinAltitude() == null) ? 0 : getMinAltitude().hashCode());
        result = prime * result + ((getMaxLongitude() == null) ? 0 : getMaxLongitude().hashCode());
        result = prime * result + ((getMinLongitude() == null) ? 0 : getMinLongitude().hashCode());
        result = prime * result + ((getMaxLatitude() == null) ? 0 : getMaxLatitude().hashCode());
        result = prime * result + ((getMinLatitude() == null) ? 0 : getMinLatitude().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_total
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", distance=").append(distance);
        sb.append(", maxSpeed=").append(maxSpeed);
        sb.append(", averageSpeed=").append(averageSpeed);
        sb.append(", maxAltitude=").append(maxAltitude);
        sb.append(", minAltitude=").append(minAltitude);
        sb.append(", maxLongitude=").append(maxLongitude);
        sb.append(", minLongitude=").append(minLongitude);
        sb.append(", maxLatitude=").append(maxLatitude);
        sb.append(", minLatitude=").append(minLatitude);
        sb.append("]");
        return sb.toString();
    }
}