package com.elite.cirworld.persist.model;

import java.util.Date;

public class CyclingPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.end_tiem
     *
     * @mbggenerated
     */
    private Date endTiem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.start_longitude
     *
     * @mbggenerated
     */
    private Float startLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.end_longitude
     *
     * @mbggenerated
     */
    private Float endLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.start_latitude
     *
     * @mbggenerated
     */
    private Float startLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_plan.end_latitude
     *
     * @mbggenerated
     */
    private Float endLatitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.id
     *
     * @return the value of cycling_plan.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.id
     *
     * @param id the value for cycling_plan.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.uid
     *
     * @return the value of cycling_plan.uid
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.uid
     *
     * @param uid the value for cycling_plan.uid
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.start_time
     *
     * @return the value of cycling_plan.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.start_time
     *
     * @param startTime the value for cycling_plan.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.end_tiem
     *
     * @return the value of cycling_plan.end_tiem
     * @mbggenerated
     */
    public Date getEndTiem() {
        return endTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.end_tiem
     *
     * @param endTiem the value for cycling_plan.end_tiem
     * @mbggenerated
     */
    public void setEndTiem(Date endTiem) {
        this.endTiem = endTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.start_longitude
     *
     * @return the value of cycling_plan.start_longitude
     * @mbggenerated
     */
    public Float getStartLongitude() {
        return startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.start_longitude
     *
     * @param startLongitude the value for cycling_plan.start_longitude
     * @mbggenerated
     */
    public void setStartLongitude(Float startLongitude) {
        this.startLongitude = startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.end_longitude
     *
     * @return the value of cycling_plan.end_longitude
     * @mbggenerated
     */
    public Float getEndLongitude() {
        return endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.end_longitude
     *
     * @param endLongitude the value for cycling_plan.end_longitude
     * @mbggenerated
     */
    public void setEndLongitude(Float endLongitude) {
        this.endLongitude = endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.start_latitude
     *
     * @return the value of cycling_plan.start_latitude
     * @mbggenerated
     */
    public Float getStartLatitude() {
        return startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.start_latitude
     *
     * @param startLatitude the value for cycling_plan.start_latitude
     * @mbggenerated
     */
    public void setStartLatitude(Float startLatitude) {
        this.startLatitude = startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_plan.end_latitude
     *
     * @return the value of cycling_plan.end_latitude
     * @mbggenerated
     */
    public Float getEndLatitude() {
        return endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_plan.end_latitude
     *
     * @param endLatitude the value for cycling_plan.end_latitude
     * @mbggenerated
     */
    public void setEndLatitude(Float endLatitude) {
        this.endLatitude = endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CyclingPlan other = (CyclingPlan) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
                && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
                && (this.getEndTiem() == null ? other.getEndTiem() == null : this.getEndTiem().equals(other.getEndTiem()))
                && (this.getStartLongitude() == null ? other.getStartLongitude() == null : this.getStartLongitude().equals(other.getStartLongitude()))
                && (this.getEndLongitude() == null ? other.getEndLongitude() == null : this.getEndLongitude().equals(other.getEndLongitude()))
                && (this.getStartLatitude() == null ? other.getStartLatitude() == null : this.getStartLatitude().equals(other.getStartLatitude()))
                && (this.getEndLatitude() == null ? other.getEndLatitude() == null : this.getEndLatitude().equals(other.getEndLatitude()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTiem() == null) ? 0 : getEndTiem().hashCode());
        result = prime * result + ((getStartLongitude() == null) ? 0 : getStartLongitude().hashCode());
        result = prime * result + ((getEndLongitude() == null) ? 0 : getEndLongitude().hashCode());
        result = prime * result + ((getStartLatitude() == null) ? 0 : getStartLatitude().hashCode());
        result = prime * result + ((getEndLatitude() == null) ? 0 : getEndLatitude().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_plan
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTiem=").append(endTiem);
        sb.append(", startLongitude=").append(startLongitude);
        sb.append(", endLongitude=").append(endLongitude);
        sb.append(", startLatitude=").append(startLatitude);
        sb.append(", endLatitude=").append(endLatitude);
        sb.append("]");
        return sb.toString();
    }
}