package com.elite.cirworld.persist.model;

import java.util.Date;

public class CyclingMonth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.distance
     *
     * @mbggenerated
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.max_speed
     *
     * @mbggenerated
     */
    private Float maxSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.average_speed
     *
     * @mbggenerated
     */
    private Float averageSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.start_longitude
     *
     * @mbggenerated
     */
    private Double startLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.end_longitude
     *
     * @mbggenerated
     */
    private Double endLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.start_latitude
     *
     * @mbggenerated
     */
    private Double startLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.end_latitude
     *
     * @mbggenerated
     */
    private Double endLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycling_month.areas
     *
     * @mbggenerated
     */
    private String areas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.id
     *
     * @return the value of cycling_month.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.id
     *
     * @param id the value for cycling_month.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.uid
     *
     * @return the value of cycling_month.uid
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.uid
     *
     * @param uid the value for cycling_month.uid
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.distance
     *
     * @return the value of cycling_month.distance
     * @mbggenerated
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.distance
     *
     * @param distance the value for cycling_month.distance
     * @mbggenerated
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.max_speed
     *
     * @return the value of cycling_month.max_speed
     * @mbggenerated
     */
    public Float getMaxSpeed() {
        return maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.max_speed
     *
     * @param maxSpeed the value for cycling_month.max_speed
     * @mbggenerated
     */
    public void setMaxSpeed(Float maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.average_speed
     *
     * @return the value of cycling_month.average_speed
     * @mbggenerated
     */
    public Float getAverageSpeed() {
        return averageSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.average_speed
     *
     * @param averageSpeed the value for cycling_month.average_speed
     * @mbggenerated
     */
    public void setAverageSpeed(Float averageSpeed) {
        this.averageSpeed = averageSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.start_time
     *
     * @return the value of cycling_month.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.start_time
     *
     * @param startTime the value for cycling_month.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.end_time
     *
     * @return the value of cycling_month.end_time
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.end_time
     *
     * @param endTime the value for cycling_month.end_time
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.start_longitude
     *
     * @return the value of cycling_month.start_longitude
     * @mbggenerated
     */
    public Double getStartLongitude() {
        return startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.start_longitude
     *
     * @param startLongitude the value for cycling_month.start_longitude
     * @mbggenerated
     */
    public void setStartLongitude(Double startLongitude) {
        this.startLongitude = startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.end_longitude
     *
     * @return the value of cycling_month.end_longitude
     * @mbggenerated
     */
    public Double getEndLongitude() {
        return endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.end_longitude
     *
     * @param endLongitude the value for cycling_month.end_longitude
     * @mbggenerated
     */
    public void setEndLongitude(Double endLongitude) {
        this.endLongitude = endLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.start_latitude
     *
     * @return the value of cycling_month.start_latitude
     * @mbggenerated
     */
    public Double getStartLatitude() {
        return startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.start_latitude
     *
     * @param startLatitude the value for cycling_month.start_latitude
     * @mbggenerated
     */
    public void setStartLatitude(Double startLatitude) {
        this.startLatitude = startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.end_latitude
     *
     * @return the value of cycling_month.end_latitude
     * @mbggenerated
     */
    public Double getEndLatitude() {
        return endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.end_latitude
     *
     * @param endLatitude the value for cycling_month.end_latitude
     * @mbggenerated
     */
    public void setEndLatitude(Double endLatitude) {
        this.endLatitude = endLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycling_month.areas
     *
     * @return the value of cycling_month.areas
     * @mbggenerated
     */
    public String getAreas() {
        return areas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycling_month.areas
     *
     * @param areas the value for cycling_month.areas
     * @mbggenerated
     */
    public void setAreas(String areas) {
        this.areas = areas == null ? null : areas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CyclingMonth other = (CyclingMonth) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
                && (this.getDistance() == null ? other.getDistance() == null : this.getDistance().equals(other.getDistance()))
                && (this.getMaxSpeed() == null ? other.getMaxSpeed() == null : this.getMaxSpeed().equals(other.getMaxSpeed()))
                && (this.getAverageSpeed() == null ? other.getAverageSpeed() == null : this.getAverageSpeed().equals(other.getAverageSpeed()))
                && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
                && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
                && (this.getStartLongitude() == null ? other.getStartLongitude() == null : this.getStartLongitude().equals(other.getStartLongitude()))
                && (this.getEndLongitude() == null ? other.getEndLongitude() == null : this.getEndLongitude().equals(other.getEndLongitude()))
                && (this.getStartLatitude() == null ? other.getStartLatitude() == null : this.getStartLatitude().equals(other.getStartLatitude()))
                && (this.getEndLatitude() == null ? other.getEndLatitude() == null : this.getEndLatitude().equals(other.getEndLatitude()))
                && (this.getAreas() == null ? other.getAreas() == null : this.getAreas().equals(other.getAreas()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getDistance() == null) ? 0 : getDistance().hashCode());
        result = prime * result + ((getMaxSpeed() == null) ? 0 : getMaxSpeed().hashCode());
        result = prime * result + ((getAverageSpeed() == null) ? 0 : getAverageSpeed().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getStartLongitude() == null) ? 0 : getStartLongitude().hashCode());
        result = prime * result + ((getEndLongitude() == null) ? 0 : getEndLongitude().hashCode());
        result = prime * result + ((getStartLatitude() == null) ? 0 : getStartLatitude().hashCode());
        result = prime * result + ((getEndLatitude() == null) ? 0 : getEndLatitude().hashCode());
        result = prime * result + ((getAreas() == null) ? 0 : getAreas().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycling_month
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", distance=").append(distance);
        sb.append(", maxSpeed=").append(maxSpeed);
        sb.append(", averageSpeed=").append(averageSpeed);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", startLongitude=").append(startLongitude);
        sb.append(", endLongitude=").append(endLongitude);
        sb.append(", startLatitude=").append(startLatitude);
        sb.append(", endLatitude=").append(endLatitude);
        sb.append(", areas=").append(areas);
        sb.append("]");
        return sb.toString();
    }
}